### ISSUE TITLE
Post List/:id 

### ISSUE THREAD

**Issue by chappy2** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#15]
When i want to change the name of the list (should this be possible? or should a given list name not beeditable?) it creates a new list with the "new name". If don't change the name of the list and only change visibility, it throws an error, duplicate key entry.

**Comment by juanmi108** [comment]
post/:id creates the list now if it does not exist

**Comment by chappy2** [comment]
The creation of a list is not the problem (i do that with post /list).I want to edit a list. The first question was, should it be allowed to change the name of the list? The main problem is, that i can't update a list (change visibility, color) is not possible. It returns this error:
"E11000 duplicate key error index: superglobalhypermeganet.lists.$_name_1 dup key: { : "color test" }"

When i change the name it creates a new list (it did that before the fix), but thats not supposed to happen. (it is triggered in the ListEdit.hmtl)

**Comment by juanmi108** [comment]
yes we should allow to change list name and co. the name of a list is no longer a unique index. name and owner is a compund key now. the owner is also a single-field index.
