### ISSUE TITLE
I think we need a array for owner

### ISSUE THREAD

**Issue by chappy2** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#25]
Andere Anwender können dann mithilfe eines Dropdownmenüs alle public Listen
einsehen und bei der Auswahl einer Liste, wird diese der Board hinzugefügt.
○ Der Anwender kann dort ebenfalls ToDo’s anlegen oder verändern.

**Comment by juanmi108** [comment]
I think we should rather, list to have the same name if the user is not the same

**Comment by chappy2** [comment]
okay. Sounds good.

**Comment by juanmi108** [comment]
fixed by #28 and 863abfc
