### ISSUE TITLE
No clue waht the second part means

### ISSUE THREAD

**Issue by chappy2** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#26]
Zu 2: In den Listen Privat und Work Backlog speichert der Anwender seine
kompletten ToDos. Aus denen kann er sich optimalerweise dann seine
TagesToDo
Liste selbst erstellen.

I'm working on the Default Lists. What means "Aus denen kann er sich optimalerweise dannseine TagesToDo Liste selbst erstellen"?????????

**Comment by juanmi108** [comment]
ich glaube sie meinte mann soll aus den Todos die in den Listen bereits existieren, andere Listen erstellen können.

**Comment by chappy2** [comment]
Okay also Todos kopieren und in eine andere Liste übernehmen? Dann überleg ich mir mal, wie man das in der view umsetzen könnte
