### ISSUE TITLE
Consider dropping Todos collection

### ISSUE THREAD

**Issue by juanmi108** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#32]
I think the todos should live inside the list a array of sub-documents.

what was the requirement that made us create the todo as a single collection anyway??

what do you think? :)

**Comment by chappy2** [comment]
i think its better. If a new todo is added to a List, we have to update the list and create a todo.

**Comment by chappy2** [comment]
I remeber why we did this. In the project description is described, that we should use a flag todos.

Another point is, that for private and work backlog to let the user select todos for todays list, it would be better if we use a todos collection.

**Comment by juanmi108** [comment]
yes but the todos could just be an array of subdocuments, and every todo can still have its flag. 
https://docs.mongodb.org/v3.0/tutorial/query-documents/#arrays

that way we can avoid joining/lookup a todos collection. we only need to make sure we deleted the todo from the list it was removed.

**Comment by chappy2** [comment]
ok
