### ISSUE TITLE
creation of standard list should be triggered in the fronted. 

### ISSUE THREAD

**Issue by juanmi108** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#33]
currently the get route for the lists checks for the existence of 3 different list, and then creates them if they do not exist, on 3 different callback. (touches the DB 4 times)

I think it would be cleaner if the get route does only one thing, to get all the list of the user. I think the frontend should check if the lists exist and then create them via post. 

A alternative would be to create a route for this purpose only. Again here the job of the angular controller is to check if the lists exist (by previously getting the lists) <--- drawback: we would have to change the API if we want to have a new standard list (or set an old one as not standard), the API should no need to know anything about the frontend implementation.   

what do you think?

https://github.com/juanmi108/Super-Global-Hyper-Mega-Net-nosql/blob/master/routes/list.js#L33

**Comment by chappy2** [comment]
I tried both, in the frontend and backend. I try it again from frontend tomorrow
