### ISSUE TITLE
organize the controllers, factory and services

### ISSUE THREAD

**Issue by juanmi108** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#35]
currently all the controllers are placed in a single js file. this makes debbuging and developing really hard. 
each controller should resided in its own file. 

something like this: 

https://scotch.io/tutorials/angularjs-best-practices-directory-structure

**Comment by chappy2** [comment]
i didn't merged it yet, but its done and works.

**Comment by juanmi108** [comment]
could you please make a pr or merge to master before closing the issue :)
