### ISSUE TITLE
check todo as completed on main view

### ISSUE THREAD

**Issue by juanmi108** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#40]
works but needs to trigger List.update()

**Comment by chappy2** [comment]
i changed it to ListEdit. only list/:id does update a list right?

**Comment by juanmi108** [comment]
yes. but where is the merge or pr? :)

**Comment by chappy2** [comment]
Format to link IT. Its in the open pr

**Comment by chappy2** [comment]
Forgot

**Comment by chappy2** [comment]
No fix already. There is a function missing.

**Comment by chappy2** [comment]
Forgot to Mode the Todo in the completed list

**Comment by blackryu** [comment]
Meaning xD?

**Comment by chappy2** [comment]
The list have a todos array. This array is divided in two parts completed and open (something like that). I just updated the completed status of the todo and didn't moved it, to the completed list

see #32
