### ISSUE TITLE
Edit/Delete Todo

### ISSUE THREAD

**Issue by chappy2** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#49]
In the listEditView the logik of theedit and delete todo buttons are not implementet yet

**Comment by blackryu** [comment]
-Delete Function should work (jumps in to correct functions, but doesn't actually delete todo afaik)
-don't know how to handle modals, tried copy/paste from "make new one", didn't even pop up....

**Comment by chappy2** [comment]
in main.js (Unter public/js) is a function for this modal. This is a bit tricky because of ng-route. I can do it tomorrow.
