### ISSUE TITLE
missing Script

### ISSUE THREAD

**Issue by juanmi108** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#5]
GET http://ujkk7b7578f7.juanmi108.koding.io:3000/bootflat/bootflat/js/jquery.fs.selector.min.js 

yet bootflat is installed.

**Comment by chappy2** [comment]
I'm not sure if we will need this. Thats why i didn't removed it yet. The skript is installed, but it needs a link in app.js to access the skript. It is not in the public folder.

**Comment by chappy2** [comment]
Now correctly integrated in case we need this.
