### ISSUE TITLE
Uncaught ReferenceError: $ is not defined(anonymous function) @ main.js:1 $

### ISSUE THREAD

**Issue by juanmi108** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#8]
use $(document).ready() ?

**Comment by chappy2** [comment]
main.js needs to be loaded at last script. Just putting jquery at first script is fixing the error ( see http://stackoverflow.com/questions/2075337/uncaught-referenceerror-is-not-defined). But the modal wasn't working anymore. Now it works with no error.
